### ISSUE TITLE
Corrección de texto en Wiki

### ISSUE THREAD

**Issue by carlosmart7104** [ElectronicCats/CatSat#3]
04. Vida de la Misión. 4.4 Recuperación, en la frase: "El ingeniero de Sistemas Espaciales deberá disponer de un equipo de recuperación en base a la última información de rastreo emitida por el CanSat..."
Propuesta: 
"El ingeniero de Sistemas Espaciales deberá disponer de un equipo de recuperación con base en la última información de rastreo emitida por el CanSat..."
http://www.academia.org.mx/espin/respuestas/item/con-base-en

**Comment by sabas1080** [comment]
Muchas gracias @carlosmart7104 , corregido
